USE [Gender_Declaration]
GO
/****** Object:  Table [dbo].[DIM_COUNTRY]    Script Date: 24/12/2023 10:25:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_COUNTRY](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[ISO_CODE] [nvarchar](3) NOT NULL,
	[REGION_ID] [int] NOT NULL,
 CONSTRAINT [PK_DIM_COUNTRY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_INDICATOR]    Script Date: 24/12/2023 10:25:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_INDICATOR](
	[ID] [int] NOT NULL,
	[TITLE] [nvarchar](250) NOT NULL,
	[CODE] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_INDICATOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_REGION]    Script Date: 24/12/2023 10:25:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_REGION](
	[ID] [int] NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_DIM_REGION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACT_INDICATOR_VALUE]    Script Date: 24/12/2023 10:25:09 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACT_INDICATOR_VALUE](
	[INDICATOR_ID] [int] NOT NULL,
	[COUNTRY_ID] [int] NOT NULL,
	[VALUE] [decimal](18, 10) NULL,
	[YEAR] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIM_COUNTRY]  WITH CHECK ADD  CONSTRAINT [FK_DIM_REGION] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[DIM_REGION] ([ID])
GO
ALTER TABLE [dbo].[DIM_COUNTRY] CHECK CONSTRAINT [FK_DIM_REGION]
GO
ALTER TABLE [dbo].[FACT_INDICATOR_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_DIM_COUNTRY] FOREIGN KEY([COUNTRY_ID])
REFERENCES [dbo].[DIM_COUNTRY] ([ID])
GO
ALTER TABLE [dbo].[FACT_INDICATOR_VALUE] CHECK CONSTRAINT [FK_DIM_COUNTRY]
GO
ALTER TABLE [dbo].[FACT_INDICATOR_VALUE]  WITH CHECK ADD  CONSTRAINT [FK_DIM_INDICATOR] FOREIGN KEY([INDICATOR_ID])
REFERENCES [dbo].[DIM_INDICATOR] ([ID])
GO
ALTER TABLE [dbo].[FACT_INDICATOR_VALUE] CHECK CONSTRAINT [FK_DIM_INDICATOR]
GO
